DROP TABLE IF EXISTS oldflix CASCADE;
CREATE TABLE oldflix (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	title VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	available BOOLEAN NOT NULL,
	category VARCHAR(50) NOT NULL,
	situation VARCHAR(50),
	responsible VARCHAR(255),
	check_out_date TIMESTAMP,
	delivery_date TIMESTAMP,
	CONSTRAINT pk_film PRIMARY KEY (id),
	CONSTRAINT ck_film_category CHECK (category IN ('BRONZE', 'SILVER', 'GOLD')),
	CONSTRAINT ck_film_situation CHECK (situation IN ('UP_TO_DATE', 'LATE'))
);
